### ISSUE TITLE
Game boxes expand past container when resizing browser window

### ISSUE THREAD

**Issue by matthewstocker** [Energised/PX#1]
When resizing browser window (Edge on Win 11), the game boxes go outside of the bordered div.

![image](https://github.com/Energised/PX/assets/7893727/c2901c3b-ac28-4aa8-aea1-aab4132af6cc)

**Comment by Energised** [comment]
The draggable code has now been fixed by implementing it manually rather than using a library. The board itself is fixed while the menu and instructions can now be dragged around to any position the user desires when resizing the window!
